# Generated by Django 4.2.11 on 2025-03-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200)),
                ('task_description', models.TextField(blank=True, default='')),
                ('status', models.IntegerField(choices=[(0, 'Pendente'), (1, 'Em Andamento'), (2, 'Concluido')], default=0)),
                ('conclusion_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
