# Generated by Django 4.2.11 on 2025-03-19 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_alter_task_task_description_alter_task_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 11, 45, 25, 374439, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.TextField(blank=True, default='', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_title',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
    ]
