# Generated by Django 4.2.11 on 2025-03-19 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_task_created_date_alter_task_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 12, 29, 39, 963148, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Criado em'),
        ),
    ]
