# Generated by Django 4.2.11 on 2025-03-19 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_alter_task_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 13, 23, 17, 425271, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Criado em'),
        ),
    ]
