# Generated by Django 4.2.11 on 2025-03-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_alter_task_conclusion_date_alter_task_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='conclusion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em'),
        ),
    ]
